language: ruby
rvm:
  - 2.2
before_script:
  - gem install awesome_bot
script:
  - awesome_bot readme.md --allow-dupe --white-list http://cmr.github.io/lanes/comparison.html
notifications:
  email: false
